language: python
python:
 - "2.7"
addons:
  apt:
    packages:
      - oracle-java8-set-default  # install Java8 as required by vnu.jar

branches:
  only:
    - master

install:
 - pip install html5validator

script: html5validator --root _build/

SURGE_LOGIN='kevinsevillano9743@gmail.com'
SURGE_TOKEN='5878d0b3fb8da0f8c5d8e37fd832e1bb'

deploy:
  provider: surge
  project: ./_build/
  domain: kevinariza.surge.sh
  skip_cleanup: true
  
