language: python
python:
 - "2.7"
addons:
  apt:
    packages:
      - oracle-java8-set-default  # install Java8 as required by vnu.jar

branches:
  only:
    - master

install:
 - pip install html5validator

script: html5validator --root _build/

deploy:
  provider: surge
  project: ./_build/
  domain: kevinariza.surge.sh
  skip_cleanup: true

SURGE_LOGIN: kevinsevillano9743@gmail.com
SURGE_TOKEN: 9eaa2fd5b4c3b13724b8f411e62e1912
